### ISSUE TITLE
<a> and <li> issues

### ISSUE THREAD

**Issue by Amy-Stalter** [Amy-Stalter/masthead-semantics#1]
@thomasjbradley

Markbot isn't a huge fan of my <href>, <a> content, or <body>, even though I can't find any issues. Any help would be appreciated.
 Thank you!

![Image 2019-09-29 at 3 32 PM](https://user-images.githubusercontent.com/55193282/65838184-6d83b800-e2ce-11e9-8cbc-6b9e83b1fc89.jpg)
[Code.pdf](https://github.com/Amy-Stalter/masthead-semantics/files/3668005/Code.pdf)

**Comment by thomasjbradley** [comment]
It’s because the `<a>` tags aren’t closed, they should look like this:

```html
<li><a href="#">Stars</a></li>
```

*Notice the `</a>` after the word "Stars".*
